### ISSUE TITLE
Selecting from Service instead from Query

### ISSUE THREAD

**Issue by ItaiYosephi** [manudss/akita-filters-plugin#10]
Isn't it a bad practice selecting from Service instead from Query?

**Comment by manudss** [comment]
Hello, 

I do not not understood your question !? 
Does this concern this 'Akita Filter Plugins' plugin or does it concern Akita?

If it's about the following code example: https://github.com/manudss/akita-filters-plugin#example-to-display-the-filters-list 

The select concerns this akita filters plug-ins. A method is therefore created in the product-filters.service.ts service which calls the plugins method. It's just a way of doing it, you can also call the direct method of the plug-ins (in the example, it is accessible in the property: filtersProduct) : 
https://github.com/manudss/akita-filters-plugin/blob/master/src/app/products-filters/state/products-filters.service.ts

It is therefore different from the select used in an akita query. Here, it is the plugins which links to the store and query 'filters' which is internal to the plugins.

I don't know if that's the question?

Regards, 

Emmanuel

**Comment by chriszrc** [comment]
@manudss I think I understand @ItaiYosephi 's question. Akita's separation of concerns states very clearly that a `Query` is used for selecting data from a store, and that a `Service` is for setting data in a `Store`. 

Creating the akita filter instance in a service makes sense, especially when you're calling methods like `setFilter` since we're setting data in the filter store. But what @ItaiYosephi is rightfully pointing out is that to get the current filtered data set from the akita filter, it would more strictly follow akita conventions if the call were not from `dataTableService.filters.selectAllByFilters()`. 

The akitafilter being a plugin makes this a somewhat special case, and I'm not an expert enough with akita to suggest how to get around this. I'm guessing that rather than suggesting people add the AkitaFilter instance to a service, it should go in it's own store object, and then it would be our responsibility to add methods to our service and query classes that reference the akitafilter store class, which would contain the filters instance. Does that make any sense?

**Comment by chriszrc** [comment]
@manudss @ItaiYosephi I think I have an idea for a solution for now, you can just make two instances of the filterplugin, one in the service and one in the query class. It appears the plugin is designed to only interact with the single filters store, so it seems like this isn't causing any problems. In the query class, you can do:

```
filtersQuery = new AkitaFiltersPlugin<DataTableState>(this).filtersQuery;
selectFiltersIsEmpty$ = this.filtersQuery.selectCount().pipe(map(c=>c<1));
```

And keep the proper separation of concerns-

**Comment by manudss** [comment]
Hi Christ, 

AkitaFiltersPlugins, will create each time, a new filterQuery, and new FilterStore. So your previsous code, will not worked. 

You need to give the exact AkitaFiltersPlugin instance into you query class, then use it, in query. 

```typescript
class MyQuery extends QueryEntity {

this._akitaFilters: AkitaFiltersPlugin = null;

set akitaFilters (plugin) => this._akitaFilters = plugin;
get akitaFilters () => this._akitaFilters ? this._akitaFilters : new AkitaFiltersPlugin(); 
   [...]

   selectAllByFilters(options?: SelectAllOptionsA<E>
    | SelectAllOptionsB<E> | SelectAllOptionsC<E> |
    SelectAllOptionsD<E> | SelectAllOptionsE<E> | any): Observable<getEntityType<S>[] | HashMap<getEntityType<S>>> {
        return this.akitaFilters.selectAllByFilters(options);
   }
} 
```
And set akita filter plugins in your query class when you first create it.

Then what, I should also to thinks, would be the possibly, to specify at creatin an akitaFiltersStore, and an AkitaFiltersQuery. To have different instance AkitaFiltersPlugin instance, that share same filtersStore. 

I will also thinks about give the possibly to separate AkitaFiltersPlugin in two subclass one for store, and one for query. 
Need to thinks about this.

**Comment by chriszrc** [comment]
Hi, thanks for thinking about, yes, as I mentioned in the Edit on the comment, it did not work, for the reasons you laid out-

**Comment by chriszrc** [comment]
@manudss nice! I think this will make everyone happy
