### ISSUE TITLE
Redundant calls to server and Expression has changed error

### ISSUE THREAD

**Issue by vpallathu** [manudss/akita-filters-plugin#64]
I'm using **akita-filters-plugin** in an angular application. I came across two issues in my app which also exist in the sample/demo application for **akita-filters-plugin**. To reproduce, run the sample demo app, navigate to ```http://localhost:4949/photos``` .

**Issue 1:** 

When navigated to the **photos** page for the first time, there are 2 network calls made to ```https://jsonplaceholder.typicode.com/photos```. There should be only one ```https://jsonplaceholder.typicode.com/photos?_page=0&_limit=25``` 

![image](https://user-images.githubusercontent.com/72323243/118559338-63c1f900-b72d-11eb-93e1-b962013b53a5.png)

**Issue 2:** 

The error is below.

```Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'null'. Current value: '25'..```

![image](https://user-images.githubusercontent.com/72323243/118559711-f4003e00-b72d-11eb-8101-317270e96241.png)

I appreciate help from someone to fix this in the code.

**Comment by manudss** [comment]
Hello, 
I've seen these errors before. But they are due to the fact that we set the filters after the initialization. Because you have to wait for the page and the limit to be loaded in the code. 
You can use a pipe(skip(1)) to remove this. But it's not possible to implement this in the librairy because it could cause problems in cases, where you don't set the filters afterwards. 

But then, I don't know how to set this. Any idea? 

Maybe implement an initialized feature and once we are sure that everything is initialized, we can make the request. This will require to specify that everything is initialized. 
Need to think about it. Don't hesitate if you have suggestions.

**Comment by vpallathu** [comment]
I read this article on the [error](https://blog.angular-university.io/angular-debugging/), but I'm not sure I can use some advises given on that page to fix the issue.

Could you please tell me where I should add ```pipe(skip(1))``` to see whether the errors are suppressed? You can tell me the file name and line number.

**Comment by yoncy** [comment]
Here's an updated documentation of  NG0100: Expression has changed after it was checked https://angular.io/errors/NG0100 . You are doing a variable set too soon in the Angular lifecycle/or variable change from outside. Variable can be identified when debugging. To not interact with that, can setup a slight delay with setTimeout or a Promise.resolve to move it to another microtask & exclude from the lifecycle checks. Ofc, this is a workaround, but if you have an already complicated code base, this would be the easiest sollution.

`// To fix this "Expression was changes after it was checked", delay this set in another microtask. No big impact. More details here https://angular.io/errors/NG0100
          Promise.resolve().then(() => {
            this.isLoading = loading;
          });`

**Comment by vpallathu** [comment]
Not using the library anymore.
